services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
      - ./mig/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: abce
      POSTGRES_USER: freelance_booking_user
      POSTGRES_DB: freelance_booking

volumes:
  pg_data:
    name: "freelance_booking_pg_data"
